ТЗ 14 спринта: создать каркас приложения shareIt, создать контроллеры для /users и /items
lojiloo/java-shareit pull request #1
Opened 2024-11-04 17:20 UTC by lojiloo

2024-11-06 05:05 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item addNewItem(@RequestBody @Valid CreateItemRequest request,
Методы контроллера должны возвращать Dto, т.к. по условию ТЗ пользователи работают только с Dto. Модель от них скрыта.

2024-11-06 05:10 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (userId == itemStorage.getItemById(itemId).getOwner()) {
Лучше использовать практику написания кода, когда реакция на ошибочную ситуацию находится ближе к месту возникновения ошибки. Например,
```
if (userId != itemStorage.getItemById(itemId).getOwner()) {
    throw new ForbiddenException("Внесение изменений доступно только владельцу");
}
... далее код с позитивным путем выполнения
```

2024-11-06 05:23 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    private long id;
Лучше объектный тип, т.к. юзер может быть сначала создан, а затем ему будет присвоен идентификатор. На временном промежутке до присвоения идентификатора, логично что он должен быть null. А в текущей реализации он будет 0.

2024-11-06 05:24 UTC, VadimZharkov requested changes
Хорошая работа, можно улучшить

2024-11-06 16:35 UTC, lojiloo commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item addNewItem(@RequestBody @Valid CreateItemRequest request,
Поняла, исправила, спасибо! Немного не дожала эту идею, -- начала везде переводить на dto, а последние два почему-то оставила(

2024-11-06 16:38 UTC, lojiloo commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (userId == itemStorage.getItemById(itemId).getOwner()) {
Да, действительно, так выглядит легче для восприятия.. Исправила здесь и в подобных местах, спасибо)

2024-11-06 16:40 UTC, lojiloo commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    private long id;
Уф, в айтиме исправила, а в юзере забыла(
Сделала, благодарю)

2024-11-07 04:53 UTC, VadimZharkov approved these changes

2024-11-07 07:35 UTC, merged