реализовать контроллер для requests, разделить приложения на 2 модуля, покрыть код тестами
lojiloo/java-shareit pull request #3
Opened 2024-11-25 03:46 UTC by lojiloo

ТЗ 16

2024-11-26 07:31 UTC, VadimZharkov commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +@Service
Лучше `@Component`, технически тоже самое, что и `@Service`, но `@Service` семантически заточен на классы-реализации сервисов.

2024-11-26 07:35 UTC, VadimZharkov commented on gateway/src/main/java/ru/practicum/shareit/exceptions/ExceptionHandlers.java
Добавь еще обработку всех оставшихся потенциальных исключений Throwable  в INTERNAL_SERVER_ERROR

2024-11-26 07:39 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/booking/BookingController.java
```
      State stateFromRequest;
        try {
            stateFromRequest = State.valueOf(state);
        } catch (IllegalArgumentException e) {
            throw new BadRequestException("Неверно указан параметр запроса", e);
        }
```
лучше завернуть в служебный метод у State. Слишком загромождает метод контроллера.

2024-11-26 07:49 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/exceptions/ExceptionHandlers.java
> +}
Также добавить обработку Throwable

2024-11-26 07:49 UTC, VadimZharkov requested changes
Хорошая работа, можно улучшить

2024-11-26 09:48 UTC, lojiloo commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +@Service
Поняла спасибо

2024-11-26 10:50 UTC, lojiloo commented on server/src/main/java/ru/practicum/shareit/booking/BookingController.java
Сделала, спасибо!

2024-11-26 12:16 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/exceptions/ExceptionHandlers.java
> +}
Вот так правильно, т.к. Throwable самый базовый класс для исключений	
```
@ExceptionHandler
	@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
	public ErrorResponse handleThrowable(Throwable e) {
		log.info("500 {}", e.getMessage(), e);
		return Map.of("Внутренняя ошибка сервера: ", e.getCause());
	}
```

Да и логирование добавить в методы обработчика ошибок - хорошая практика. Поможет по логам разбираться, что же произошло.

2024-11-26 12:20 UTC, VadimZharkov requested changes
Поправь обработчик ошибок

2024-11-27 03:31 UTC, VadimZharkov approved these changes

2024-11-28 14:14 UTC, merged